@startuml
'https://plantuml.com/use-case-diagram

:業務依頼者: as Requester
:受注希望者: as CrowdWorker

Requester --> ([[./create_project.md 案件を作る]])
Requester --> (案件を公開する)
CrowdWorker --> (案件を検索する)
CrowdWorker --> (案件に応募する)
Requester --> (応募者を見る)
Requester --> (一次選考する)
Requester --> (メッセージのやりとりする)
CrowdWorker --> (メッセージのやりとりする)
Requester -> (発注先を決定する)
@enduml