@startuml
'https://plantuml.com/use-case-diagram

:業務依頼者: as Requester
:受注希望者: as CrowdWorker

Requester --> ([[./create_project.md 案件を作る]])
Requester --> ([[./publish_project.md 案件を公開する]])
CrowdWorker --> ([[./search_project.md 案件を検索する]])
CrowdWorker --> ([[./apply_project.md 案件に応募する]])
Requester --> ([[./search_crowdworker.md 応募者を見る]])
Requester --> ([[./select_crowdworker_1st_round.md 一次選考する]])
Requester -> ([[./communicate_via_messages.md メッセージのやりとりする]])
CrowdWorker -> ([[./communicate_via_messages.md メッセージのやりとりする]])
Requester --> (発注先を決定する)
@enduml